### ISSUE TITLE
Add relationships from existing?

### ISSUE THREAD

**Issue by jcmundy** [FocusVision/ember-admin#16] opened 2017-09-19 15:30 UTC
Hello, I have been working on testing out your ember-admin.  I have gotten everything working, but when I go to "Add relationships/Select from existing" it shows the relationships but cannot add them.  

My app has books, which belong to Authors and Libraries, and Libraries and Authors both have many books.  When I go to Author (or Library), I have no problem creating a new book.  Which processes in this format:

Processing by Admin::BooksController#create as JSONAPI
  Parameters: {"data"=>{"attributes"=>{"title"=>"New Book"}, "relationships"=>{"author"=>{"data"=>{"type"=>"authors", "id"=>"2"}}}, "type"=>"books"}}
   (0.2ms)  BEGIN
  SQL (1.3ms)  INSERT INTO `books` (`title`, `author_id`, `created_at`, `updated_at`) VALUES ('New Book', 2, '2017-09-19 15:26:30', '2017-09-19 15:26:30')
   (0.4ms)  COMMIT

But when I try to add an existing book to an author, it uses this format:

Processing by Admin::BooksController#create as JSONAPI
  Parameters: {"data"=>[{"type"=>"books", "id"=>"7"}], "author_id"=>"3"}
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `books` (`created_at`, `updated_at`) VALUES ('2017-09-19 15:27:31', '2017-09-19 15:27:31')
   (1.0ms)  COMMIT

And ends up creating an empty unattached book.  I am not sure if there is a bug or if I have something wrong in my code.  What could I be doing?  Thank you for your help!

**Comment by rsullivan00** [comment] 2017-09-19 16:27
Hi @jcmundy. Ember Admin uses [JSONAPI relationships routes](http://jsonapi.org/format/#crud-updating-to-many-relationships) when updating relationships.

For a has-many relationship (like your Author -> Books relationship), the expected behavior is to send a `POST` request to the `/authors/:author_id/relationships/books` route with body
```js
{ data: [{ id: 7, type: 'books' }] }
```

It looks like that is happening, but your API doesn't have the relationship routes properly implemented. Many JSONAPI libraries have configuration options to add these routes automatically; try checking to see if you can enable them.

**Comment by jcmundy** [comment] 2017-09-20 16:31
Thank you.  In my Rails routes.rb I put the following:
```      
        resources :authors do
         resources :books, path: 'relationships/books'
        end
```
Do you know if that is the correct way to add a route for /relationships/?  Otherwise my app was not finding it.

**Comment by rsullivan00** [comment] 2017-09-20 16:52
The Rails `resources` route helper doesn't create all JSON API routes.

We use the [JSONAPI::Resources](https://github.com/cerebris/jsonapi-resources/) gem for building JSON API compliant apis with Rails. It provides a `jsonapi_resources` route helper that will do what you're looking for.

I'm going to close this issue, since this isn't an issue with Ember Admin.

**Closed as completed by rsullivan00** 2017-09-20 16:52 UTC

**Comment by jcmundy** [comment] 2017-09-20 21:28
Thanks, that did it.
